### ISSUE TITLE
1.18 File on curseforge has 1.17.1 in it

### ISSUE THREAD

**Issue by ghost** [Phylogeny/JEIEnchantmentInfo#7]
On curseforge uploaded file for version 1.18 has 1.17.1 in the name 
JEIEnchantmentInfo-1.17.1-2.0.0.jar

**Comment by Phylogeny** [comment]
That's because the 1.17 release also runs in 1.18, and is tagged as such. Building against 1.18 and doing the same was not an option, since 1.17 is compiled in Java 16 and 1.18 in Java 17; but even if I had, there still would have been one release for both versions with a jar filename corresponding to the version it was built against.
